// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    if (node.left.type === 'Identifier') {
      return this.recurseAll([node.left, node.right], node, callback, (function(_this) {
        return function(err, _arg) {
          var property, value;
          property = _arg[0], value = _arg[1];
          return callback(null, _this.context[property] = value);
        };
      })(this));
    } else {
      return this.recurseAll([node.left.object, node.left.property, node.right], node, callback, function(err, _arg) {
        var object, property, value;
        object = _arg[0], property = _arg[1], value = _arg[2];
        object[property] = value;
        return callback(null, value);
      });
    }
  };

}).call(this);

//# sourceMappingURL=AssignmentExpression.map
