// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return this.recurseAll([node.left, node.right], node, callback, (function(_this) {
      return function(err, _arg) {
        var left, right;
        left = _arg[0], right = _arg[1];
        switch (node.operator) {
          case '+':
            return callback(null, left + right);
          case '-':
            return callback(null, left - right);
          case '*':
            return callback(null, left * right);
          case '/':
            return callback(null, left / right);
          default:
            return callback('Undefined BinaryExpression operator: ' + node.operator);
        }
      };
    })(this));
  };

}).call(this);

//# sourceMappingURL=BinaryExpression.map
