// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return this.recurseAll(node.body, node, callback, callback);
  };

}).call(this);

//# sourceMappingURL=BlockStatement.map
