// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return this.recurse(node.expression, node, callback, callback);
  };

}).call(this);

//# sourceMappingURL=ExpressionStatement.map
