// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return node.context.get(node.name, callback);
  };

}).call(this);

//# sourceMappingURL=Identifier.map
