// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return this.get([node.name], node.context, callback, function(err, _arg) {
      var res;
      res = _arg[0];
      return callback(null, res);
    });
  };

}).call(this);

//# sourceMappingURL=Identifier.map
