// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    var _ref;
    if ((_ref = node.operator) !== '&&' && _ref !== '||') {
      callback('Undefined LogicalExpression operator: ' + node.operator);
    }
    node.left.parent = node;
    node.right.parent = node;
    return this.recurse(node.left, node, callback, (function(_this) {
      return function(err, left) {
        if (err) {
          return callback(err);
        }
        if (!left && node.operator === '&&') {
          return callback(null, false);
        }
        if (left && node.operator === '||') {
          return callback(null, left);
        }
        return _this.recurse(node.right, node, callback, function(err, right) {
          if (err) {
            return callback(err);
          }
          return callback(null, right || left);
        });
      };
    })(this));
  };

}).call(this);

//# sourceMappingURL=LogicalExpression.map
