// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return this.recurse(node.object, node, callback, (function(_this) {
      return function(err, object) {
        node.property.context = new _this.constructor.Context(node.context, object);
        return _this.recurse(node.property, node, callback, function(err, value) {
          return callback(null, value);
        });
      };
    })(this));
  };

}).call(this);

//# sourceMappingURL=MemberExpression.map
