// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  module.exports = function(node, callback) {
    return this.recurseAll([node.callee].concat(node["arguments"]), node, callback, function(err, _arg) {
      var args, callee, fn, key, obj;
      callee = _arg[0], args = 2 <= _arg.length ? __slice.call(_arg, 1) : [];
      obj = (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(callee, args, function(){});
      for (key in obj) {
        fn = obj[key];
        if (typeof fn === 'function') {
          obj[key] = fn.bind(obj);
        }
      }
      return callback(null, obj);
    });
  };

}).call(this);

//# sourceMappingURL=NewExpression.map
