// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    node.context = new this.constructor.Context(node.context, {});
    return this.recurseAll(node.properties, node, callback, function(err) {
      return callback(err, node.context.data);
    });
  };

}).call(this);

//# sourceMappingURL=ObjectExpression.map
