// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return node.context.get('this', callback);
  };

}).call(this);

//# sourceMappingURL=ThisExpression.map
