// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    return callback(null, this.context["this"]);
  };

}).call(this);

//# sourceMappingURL=ThisExpression.map
