// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    node.argument.parent = node;
    return this.recurse(node.argument, node, callback, function(err, argument) {
      switch (node.operator) {
        case '-':
          return callback(null, -argument);
        case '+':
          return callback(null, +argument);
        case '!':
          return callback(null, !argument);
        case 'typeof':
          return callback(null, typeof argument);
        case 'void':
          return callback(null, void 0);
        default:
          return callback('Undefined UnaryExpression operator: ' + node.operator);
      }
    });
  };

}).call(this);

//# sourceMappingURL=UnaryExpression.map
