// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(node, callback) {
    var cb, do_loop;
    node.test.parent = node;
    node.body.parent = node;
    cb = (function(_this) {
      return function(err) {
        if (err === 'break') {
          return callback();
        }
        if (err) {
          return callback(err);
        }
        return do_loop();
      };
    })(this);
    return (do_loop = (function(_this) {
      return function() {
        return _this.recurse(node.test, node, callback, function(err, pass) {
          if (pass) {
            return callback();
          }
          return _this.recurse(node.body, node, cb, cb);
        });
      };
    })(this))();
  };

}).call(this);

//# sourceMappingURL=WhileStatement.map
